FROM node:18 AS react-build

ENV PROJECT=sidequest

RUN mkdir /${PROJECT}
WORKDIR /${PROJECT}/

COPY ./sidequest/package.json /${PROJECT}/
COPY ./sidequest/package-lock.json /${PROJECT}/
RUN npm install

COPY sidequest /${PROJECT}

RUN npm run build

FROM nginx:alpine

ENV PROJECT=sidequest

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=react-build /${PROJECT}/build /usr/share/nginx/html
EXPOSE 80