---

services: 
  sq-flask:
    image: jdolakk/sidequest-flask
    env_file: ../../.env
    restart: none
    deploy:
      resources:    
        limits:
          memory: 200MB

  sq-frontend:
    image: jdolakk/sidequest-frontend
    env_file: ../../.env
    ports:
      - ${HOST_PORT}:80
