---

services: 
  sq-flask:
    image: jdolakk/sidequest-flask
    env_file: ../../.env
    ports:
      - ${HOST_PORT}:${APP_PORT}
    restart: on-failure
    deploy:
      resources:    
        limits:
          memory: 200MB

  sq-nginx:
    image: jdolakk/sidequest-frontend
    ports:
      - "80:80"
#    volumes:
#      - ../nginx.conf:/etc/nginx/nginx.conf
#      - ./html:/usr/share/nginx/html

