CREATE TABLE SQ_USERS (
    user_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username VARCHAR2(255) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL
);

CREATE TABLE SQ_GROUPS (
    group_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    group_name VARCHAR2(255) NOT NULL,
    group_desc VARCHAR2(4000),
    is_public CHAR(1) CHECK (is_public IN ('Y', 'N')),
    invite_code CHAR(64) UNIQUE
    default_currency NUMBER,
);

CREATE TABLE SQ_GROUPS_USER (
    user_id NUMBER,
    group_id NUMBER,
    currency NUMBER,
    role VARCHAR2(255),
    PRIMARY KEY (user_id, group_id),
    FOREIGN KEY (user_id) REFERENCES SQ_USERS(user_id) ON DELETE CASCADE,
    FOREIGN KEY (group_id) REFERENCES SQ_GROUPS(group_id) ON DELETE CASCADE
);

CREATE TABLE AVAILABLE_BETS (
    bet_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    group_id NUMBER,
    seller_id NUMBER,
    max_quantity NUMBER,
    side CHAR(1) CHECK (side IN ('Y', 'N')),
    odds NUMBER,
    question VARCHAR2(4000) NOT NULL,
    description VARCHAR2(4000),
    status VARCHAR2(255),
    FOREIGN KEY (group_id) REFERENCES SQ_GROUPS(group_id) ON DELETE CASCADE,
    FOREIGN KEY (seller_id) REFERENCES SQ_USERS(user_id) ON DELETE CASCADE
);

CREATE TABLE BOUGHT_BETS (
    buyer_id NUMBER,
    bet_id NUMBER,
    quantity NUMBER NOT NULL,
    side CHAR(1) CHECK (side IN ('Y', 'N')),
    status VARCHAR2(255),
    date_bought TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    date_resolved DATE,
    submission_photo VARCHAR2(4000),
    PRIMARY KEY (buyer_id, bet_id),
    FOREIGN KEY (buyer_id) REFERENCES SQ_USERS(user_id) ON DELETE CASCADE,
    FOREIGN KEY (bet_id) REFERENCES AVAILABLE_BETS(bet_id) ON DELETE CASCADE
);

CREATE TABLE QUESTS (
    quest_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    author_id NUMBER,
    group_id NUMBER,
    quest_title VARCHAR2(255) NOT NULL,
    quest_desc VARCHAR2(4000),
    reward_amount NUMBER NOT NULL,
    due_date DATE,
    quest_status VARCHAR2(255) NOT NULL,
    FOREIGN KEY (author_id) REFERENCES SQ_USERS(user_id) ON DELETE CASCADE,
    FOREIGN KEY (group_id) REFERENCES SQ_GROUPS(group_id) ON DELETE CASCADE
);

CREATE TABLE QUEST_SUBMISSIONS (
    submission_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    quest_id NUMBER,
    submission_photo VARCHAR2(4000),
    submission_date_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    comments VARCHAR2(4000),
    status VARCHAR2(255) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES SQ_USERS(user_id) ON DELETE CASCADE,
    FOREIGN KEY (quest_id) REFERENCES QUESTS(quest_id) ON DELETE CASCADE
);
