
DROP TABLE QUEST_SUBMISSIONS CASCADE CONSTRAINTS;
DROP TABLE BOUGHT_BETS CASCADE CONSTRAINTS;
DROP TABLE AVAILABLE_BETS CASCADE CONSTRAINTS;
DROP TABLE QUESTS CASCADE CONSTRAINTS;
DROP TABLE GROUPS_USER CASCADE CONSTRAINTS;

DROP TABLE GROUPS CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;